name: Lint subtitles

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  timedtext-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: electrosparklez/timedtext-lint@main
        with:
          paths: |
            subtitles/
            captions/intro.vtt
          config: .timedtextlintrc.json
